services:
  - type: web
    name: comsierge-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: postgresql://comsierge_user:0bzGlid9MyN4dK4eF4igKciTMkVKpsRb@dpg-d1qmcsodl3ps73933470-a/comsierge
      - key: JWT_SECRET
        value: RANDOMSECRETKEY
      - key: PORT
        value: 3000
      - key: TWILIO_SMS_WEBHOOK_URL
        value: https://57286b692651.ngrok-free.app
        
  - type: static
    name: comsierge-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: out  #  'out' for Next.js export
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://comsierge-backend.onrender.com


  - type: cron
    name: message-scheduler
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node cron/sendScheduledMessages.js
    schedule: "*/5 * * * *"  # Every 5 minutes
    envVars:
      - key: DATABASE_URL
        value: postgresql://comsierge_user:0bzGlid9MyN4dK4eF4igKciTMkVKpsRb@dpg-d1qmcsodl3ps73933470-a/comsierge
      - key: JWT_SECRET
        value: RANDOMSECRETKEY
